on:
  push:
    branches:
    - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Deploy canisters
      id: deploy
      uses: fleekhq/ic-deploy-action@v2
      run: |
        wget https://github.com/dfinity/vessel/releases/download/v0.6.4/vessel-linux64
        mv vessel-linux64 vessel
        chmod +x vessel
      with:
        identity: ${{ secrets.DFX_IDENTITY }}
        wallets: ${{ secrets.DFX_WALLETS }}
        dfx_params: --no-wallet
    - uses: MCJack123/ghaction-generate-release-hashes@v3
      with:
        hash-type: sha256
        file-name: canister.wasm
    - uses: actions/upload-artifact@v2
      with:
        name: wasm Hash
        path: .dfx/ic/canisters/dao/dao.wasm
    - name: Show success message
      run: echo success!
